name: Auto fetch SZVÖRs
'on':
  schedule:
    - cron: 0 14 * */1 *
  workflow_dispatch: null
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Setup git
        run: |
          git switch main
          git config --global user.name "SzVÖR Updater"
          git remote set-url --push origin https://d3n972:${GITHUB_TOKEN}@github.com/D3nWorks/szvor-csv.git
          git checkout main
      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: 17
          distribution: temurin
          java-package: jre
      - name: Get current date
        id: date
        run: 'echo "::set-output name=date::$(date +''%Y-%m-%d'')"'
      - name: Install dependencies
        run: >
          sudo apt update&&sudo apt install wget curl -y&&
          wget "https://github.com/tabulapdf/tabula-java/releases/download/v1.0.5/tabula-1.0.5-jar-with-dependencies.jar"
      - name: Fetch szvör pdfs
        run: >
          wget -l 1 -A pdf  --limit-rate=250k --mirror
          https://www.mavcsoport.hu/mav-start/bemutatkozas/belfoldi-utazas/vonatosszeallitas-szvor
      - name: Extract csvs from the pdfs
        run: >
          java -jar tabula-1.0.5-jar-with-dependencies.jar -b
          www.mavcsoport.hu/sites/default/files/upload/page/ -f CSV -l -o csv 
      - name: Move extracted files
        run: |
           mv www.mavcsoport.hu/sites/default/files/upload/page/*.csv csv/
           rm tabula-1.0.5-jar-with-dependencies.jar 
      - name: Rename files
        run: |
          workdir=$(pwd)
          cd $workdir/csv
          for f in $(ls *.csv); do
              dst=$(echo $f| sed 's/[0-9]*//g'|sed 's/_\.csv/\.csv/g')      
              updated_at=$(echo $f|grep -oP "\d{6,8}")
              mv $f $workdir/csv/$dst                                                    
              git add -- $(git status --short |grep -P  '(??|A|M)' |cut -d' ' -f2| xargs -i sh -c "printf '%s\n' {}")
              git commit -m "$dst updated at: $updated_at"||echo "no change"
          done
          git push -u origin main
      - uses: actions/upload-artifact@v3
        with:
          name: 'szvor-${{ steps.date.outputs.date }}'
          path: csv/
      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
           # The arguments for the `git add` command (see the paragraph below for more info)
           # Default: '.'
           add: 'csv'
           # The name of the user that will be displayed as the author of the commit.
           # Default: depends on the default_author input
           author_name: SzVÖR collector

           # The email of the user that will be displayed as the author of the commit.
           # Default: depends on the default_author input
           author_email: szvor@noreply.net
           # Determines the way the action fills missing author name and email. Three options are available:
           # - github_actor -> UserName <UserName@users.noreply.github.com>
           # - user_info -> Your Display Name <your-actual@email.com>
           # - github_actions -> github-actions <email associated with the github logo>
           # Default: github_actor
           default_author: github_actor

           # The message for the commit.
           # Default: 'Commit from GitHub Actions (name of the workflow)'
           message: 'Update SzVÖRs ${{ steps.date.outputs.date }}'
           # The way the action should handle pathspec errors from the add and remove commands. Three options are available:
           # - ignore -> errors will be logged but the step won't fail
           # - exitImmediately -> the action will stop right away, and the step will fail
           # - exitAtEnd -> the action will go on, every pathspec error will be logged at the end, the step will fail.
           # Default: ignore
           pathspec_error_handling: ignore
           # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
           # Default: true
           push: true
