name: Auto fetch SZVÖRs
'on':
  schedule:
    - cron: 0 14 * */1 *
  workflow_dispatch: null
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: 17
          distribution: temurin
          java-package: jre
      - name: checkout code
        uses: actions/checkout@v1
      - name: Get current date
        id: date
        run: 'echo "::set-output name=date::$(date +''%Y-%m-%d'')"'
      - name: Install dependencies
        run: >
          apt update&&apt install wget curl -y

          wget
          "https://github.com/tabulapdf/tabula-java/releases/download/v1.0.5/tabula-1.0.5-jar-with-dependencies.jar"
      - name: Fetch szvör pdfs
        run: >
          wget -l 1 -A pdf  --limit-rate=150k --mirror
          https://www.mavcsoport.hu/mav-start/bemutatkozas/belfoldi-utazas/vonatosszeallitas-szvor
      - name: Extract csvs from the pdfs
        run: >
          java -jar tabula-1.0.5-jar-with-dependencies.jar -b
          www.mavcsoport.hu/sites/default/files/upload/page/ -f CSV -l -o csv 
      - name: Move extracted files
        run: |
          mkdir csv
          mv www.mavcsoport.hu/sites/default/files/upload/page/*.csv csv/
      - name: Setup git
        run: |
          #git switch main
          git config --global user.name "SzVÖR Updater"
      - name: Rename files
        run: |
          cd csv/
          for f in $(ls *.csv); do
              dst=$(echo $f| sed 's/[0-9]*//g'|sed 's/_\.csv/\.csv/g')      
              updated_at=$(echo $f|grep -oP "\d{6,8}")
              mv $f $dst                                                    
              git add $dst 
              git commit --allow-empty -m "$dst updated at: $updated_at"
          done
          git remote set-url --push origin https://d3n972:${GITHUB_TOKEN}@github.com/D3nWorks/szvor-csv.git
          git push -u origin main
      - uses: actions/upload-artifact@v3
        with:
          name: 'szvor-${{ steps.date.outputs.date }}'
          path: csv/
